{{ config(materialized='view') }}

WITH CUSTOMERORDER AS (
    SELECT 
        C.CUSTOMERID::VARCHAR AS CUSTOMERID,
        CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
        COUNT(O.ORDERID) AS ORDERCOUNT
    FROM {{ source('landing', 'customers') }}  C
    LEFT JOIN {{ source('landing', 'orders') }} O ON TRIM(C.CUSTOMERID) = TRIM(O.CUSTOMERID)

    GROUP BY C.CUSTOMERID, CUSTOMERNAME
)
SELECT 
    CUSTOMERID,
    CUSTOMERNAME,
    ORDERCOUNT
FROM CUSTOMERORDER
ORDER BY ORDERCOUNT DESC
